[theme]
base = "light"
primaryColor = "#b11f4b"
backgroundColor = "#f7f4ef"
secondaryBackgroundColor = "#ffffff"
textColor = "#242424"
font = "sans serif"

[server]
maxUploadSize = 10
headless = true

[browser]
gatherUsageStats = false
